HOME_DIRECTORY = "/home/pi"
LOG_DIRECTORY = HOME_DIRECTORY + "/Tracks"
ORIGINAL_LOG_DIRECTORY = HOME_DIRECTORY + "/Tracks/Original"
GPX_LOG_DIRECTORY = HOME_DIRECTORY + "/Tracks/GPX"
COLOR_MODE_FILE = HOME_DIRECTORY + "/color_mode.txt"
DROPBOX_KEY_FILE = HOME_DIRECTORY + "/dropbox_key.txt"
BACKGROUND_COLOR = "white"
TEXT_COLOR = "black"

GPS_SERIAL_PORT = "/dev/ttyAMA0"
GPS_BAUD_RATE = 38400 # 38400, 230400

OBD_SERIAL_PORT = "/dev/ttyUSB0"
OBD_BAUD_RATE = 9600

class GPSMessages:
	UBX_NAV_PVT = "UBX-NAV-PVT"

class OBDTypes:
	RPM = "RPM"
	COOLANT_TEMP = "COOLANT_TEMP"
	ENGINE_LOAD = "ENGINE_LOAD"
	AMBIANT_AIR_TEMP = "AMBIANT_AIR_TEMP"
	THROTTLE_POS = "THROTTLE_POS"
	FUEL_STATUS = "FUEL_STATUS"
	INTAKE_PRESSURE = "INTAKE_PRESSURE"
	TIMING_ADVANCE = "TIMING_ADVANCE"
	INTAKE_TEMP = "INTAKE_TEMP"
	
	@staticmethod
	def getAllTypes():
		return [attr for attr in dir(OBDTypes) if not callable(getattr(OBDTypes, attr)) and not attr.startswith("__")]
